# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference
name: My Config
version: 0.0.1
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Gemini 3.1 Pro Preview
    provider: vertexai
    model: gemini-3.1-pro-preview
    env:
      projectId: amiable-anagram-495103-c4
      region: global

  - name: Gemini 3 Flash Preview
    provider: vertexai
    model: gemini-3-flash-preview
    env:
      projectId: amiable-anagram-495103-c4
      region: global
# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools